esphome:
  name: water_storage

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "way"
  password: !secret waypassword

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water Storage Fallback Hotspot"
    password: "ybQIeIStGa7J"

captive_portal:
    