esphome:
  name: water_storage

esp8266:
  board: d1_mini

logger:

api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

captive_portal:

web_server:
  port: 80

sensor:
  - platform: ultrasonic
    name: "Ultrasonic sensor"
    trigger_pin: D1
    echo_pin: D2
    update_interval: 10s
    timeout: 20m
    filters:
      - median:
          window_size: 5
          send_every: 3
          send_first_at: 2
