esphome:
  name: water_storage

esp8266:
  board: d1_mini

logger:

api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

captive_portal:

web_server:
  port: 80

sensor:
  - platform: ultrasonic
    name: "Ultrasonic sensor"
    trigger_pin: GPIO1
    echo_pin: GPIO3
    update_interval: 1s
    timeout: 20m
